### ISSUE TITLE
meta: re-architect Kartoza web stack

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#187]
# Problem

Each time we start a new Kartoza or client site we have been forking docker-mezzanine and customising each instance. 
1. this is not clever nor sustainable
1. we want to build a slick, stable, multifunctional, up-to-date core stack that is easy to deploy and extend

# Proposed solution
- [ ] separate static and other localised content in downstream sites from docker-mezzanine in preparation for the next step. 
- [ ] merge extended apps and fixes from downstream back upstream to this fork so that we have a generic stack with a suite of working, pluggable apps (Cartridge, Symposion, etc)
- [ ] update all components so we have the latest stable version of each
- [ ] design a workflow for creating new sites with docker-mezzanine as core, in a way that upstream fixes can easily be pulled in and downstream improvements and fixes can easily be pushed up. 
  - pull image and add localisations?
  - install from Pypi and localise?
- [ ] using the above workflow, split out 
  - https://github.com/kartoza/kartoza.com/issues/1 
  and  update
  - qgis.org.za with foss4g-africa.org (on same instance with Django sites) https://github.com/kartoza/qgis.org.za/issues/79
- [ ] configure this generic web stack in https://github.com/kartoza/kartoza-rancher-catalogue
 
![kartoza_web_stack_overview](https://cloud.githubusercontent.com/assets/496911/25940556/cad0ec0e-3636-11e7-9037-9fb76d12a9e3.png)
(original https://github.com/kartoza/docker-mezzanine/blob/develop/django_project/kartoza_web_stack_overview.graffle)

cc @cchristelis @timlinux

**Comment by gubuntu** [comment]
use github submodules?
